name: Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose deployment environment
        required: true
        type: choice
        options:
          - all
          - dev
          - stage
          - prod
        default: all

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    if: inputs.environment == 'all' || inputs.environment == 'dev'
    environment: dev

    steps:
      - name: Deploy to dev
        run: echo "deployed on dev"

  deploy_stage:
    runs-on: ubuntu-latest
    if: inputs.environment == 'all' || inputs.environment == 'stage'
    environment: stage

    steps:
      - name: Deploy to stage
        run: echo "deployed on stage"

  deploy_prod:
    runs-on: ubuntu-latest
    if: inputs.environment == 'all' || inputs.environment == 'prod'
    environment: prod

    steps:
      - name: Deploy to prod
        run: echo "deployed on prod"
