name: Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose deployment environment
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
        default: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Deploy to selected environment
        run: echo "deployed on ${{ inputs.environment }}"
